---
title: "USTM Resiliency Sensitivity Analysis"
author:
  - name: Gregory Macfarlane
    email: gregmacfarlane@byu.edu
    affiliation: Brigham Young University
    footnote: 1
  - name: Natalie Gray
    email: nat.gray2000@gmail.com
    affiliation: Brigham Young University
address:
  - code: Brigham Young University
    address: Civil and Environmental Engineering Department, 430 Engineering Building, Provo, Utah 84602
footnote:
  - code: 1
    text: "Corresponding Author"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
journal: "Submitted to Journal"
bibliography: [book.bib]
layout: "3p, authoryear, review"
biblio-style: apalike
link-citations: yes
abstract: |
  The input parameters used in travel demand models contribute to result uncertainty. A coefficient of variation was used to determine the range of possible values for each parameter. Sampling methods can approximate a normal distribution of parameter values with a discrete number of draws. This paper looks at Monte Carlo sampling and Latin Hypercube sampling. A three-step travel demand model is created with a 25-zone dummy model to evaluate if Latin Hypercube sampling reduces the number of draws needed to approximate Monte Carlo sampling. The mean modechoice logsum value was used to evaluate a cumulative standard deviation of values based upon 100 and 600 draws of parameter values for each sampling method. The standard deviation for Latin hypercube samples stabilize between 100 and 200 draws, whereas Monte Carlo samples often haven't stabilized at 600 draws. Latin hypercube sampling does reduce the number of draws needed, to where it can be applied to a large-scale model.
description: "Sensitivity analysis of input parameters on a 25-zone dummy model."
keywords:
  - Sensitivity Analysis,
  - Resiliency,
  - Latin Hypercube Sampling
---

```{r, include = FALSE}
library(targets)
library(readxl)
library(tidyverse)
library(knitr)
library(targets)
library(gridExtra)
```


# Questions

There exists uncertainty in travel demand models. This is known by transportation planners but the majority do not use any particular method to quantify it. This uncertainty exists to some extent by the variance among input parameters. Two popular sampling methods to draw from the range of possible parameters are Monte Carlo (MC) simulation and Latin Hypercube Sampling (LHS). MC simulation requires large computations to be effective on a statewide model. LHS reduces the number of variants needed, but the amount of reduction is unknown. [@yang2013sensitivity]

The research questions are therefore:

  - Using a dummy travel demand model, can Latin Hypercube Sampling reduce the iterations needed to approximate random sampling methods (e.g., Monte Carlo simulation)?
  - Does this method of sampling have few enough iterations for statewide model application?
